version: '3.8'

services:
  # Main Application (Free hosting compatible)
  app:
    build: .
    container_name: shiftadjuster-app-free
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3000
      
      # Use external free database service (Supabase/PlanetScale/Neon)
      DB_HOST: ${EXTERNAL_DB_HOST}
      DB_PORT: ${EXTERNAL_DB_PORT:-5432}
      DB_NAME: ${EXTERNAL_DB_NAME}
      DB_USER: ${EXTERNAL_DB_USER}
      DB_PASSWORD: ${EXTERNAL_DB_PASSWORD}
      DB_SSL: true
      
      # Use external Redis service (Upstash/Redis Labs free tier)
      REDIS_HOST: ${EXTERNAL_REDIS_HOST}
      REDIS_PORT: ${EXTERNAL_REDIS_PORT:-6379}
      REDIS_PASSWORD: ${EXTERNAL_REDIS_PASSWORD}
      REDIS_TLS: true
      
      # Security
      JWT_SECRET: ${JWT_SECRET}
      SESSION_SECRET: ${SESSION_SECRET}
      
      # Application
      DEFAULT_TIMEZONE: Asia/Singapore
      ENABLE_REAL_TIME: true
      ENABLE_NOTIFICATIONS: true
      ENABLE_ANALYTICS: true
      
    ports:
      - "3000:3000"
    volumes:
      - app_logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  app_logs:
    driver: local 